name: Deploy All Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          config-file: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Login to OCI Registry (Docker Hub)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy all charts
        run: helmfile apply